# Generated by Django 5.0.3 on 2024-04-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslog',
            name='keywords1',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferList',
            field=models.JSONField(default=dict),
        ),
    ]
